user-message: "WARNING: This stack project is generated."

flags:
  haskeline:
    terminfo: false

allow-different-user: true

build:
  interleaved-output: false

ghc-options:
  # All packages
  "$locals": -Wall -Werror -Wno-name-shadowing -Wno-missing-pattern-synonym-signatures -fprint-expanded-synonyms -fwrite-ide-info #-freverse-errors

  # See https://github.com/haskell/haskell-language-server/issues/208
  "$everything": -haddock


resolver: lts-20.26

# We have 32 packages.
packages:
  - ./codebase2/codebase
  - ./codebase2/codebase-sqlite
  - ./codebase2/codebase-sqlite-hashing-v2
  - ./codebase2/codebase-sync
  - ./codebase2/core
  - ./codebase2/util-serialization
  - ./codebase2/util-term
  - ./lib/orphans/network-uri-orphans-sqlite
  - ./lib/orphans/unison-core-orphans-sqlite
  - ./lib/orphans/unison-hash-orphans-aeson
  - ./lib/orphans/unison-hash-orphans-sqlite
  - ./lib/orphans/uuid-orphans-sqlite
  - ./lib/unison-hash
  - ./lib/unison-hashing
  - ./lib/unison-prelude
  - ./lib/unison-pretty-printer
  - ./lib/unison-sqlite
  - ./lib/unison-util-base32hex
  - ./lib/unison-util-bytes
  - ./lib/unison-util-cache
  - ./lib/unison-util-file-embed
  - ./lib/unison-util-nametree
  - ./lib/unison-util-relation
  - ./lib/unison-util-rope
  - ./parser-typechecker
  - ./unison-cli
  - ./unison-core
  - ./unison-hashing-v2
  - ./unison-share-api
  - ./unison-share-projects-api
  - ./unison-syntax
  - ./yaks/easytest

# We have 2 source packages:
#   * external 0
#   * internal 0
#   * external forks 2
#   * internal forks 0
extra-deps:
  # Source Packages, external (3rd party) forks of other repositories.
  # Can we help upstream?
  - git: https://github.com/unisonweb/configurator
    commit: e47e9e9fe1f576f8c835183b9def52d73c01327a
  - git: https://github.com/unisonweb/haskeline
    commit: 9275eea7982dabbf47be2ba078ced669ae7ef3d5

  # Package versions for published packages either not on Stackage or
  # not matching the version on Stackage for the resolver we use.
  # These package-version extra dependencies are equivalent to cabal constraints.
  - fuzzyfind-3.0.1
  - lock-file-0.7.0.0
  - lsp-2.0.0.0
  - lsp-types-2.0.1.1
  - monad-validate-1.3.0.0
  - recover-rtti-0.4.3
  - row-types-1.0.1.2
